<?php

return [
    'proyectos' => [
        (object) [
            'id' => 10,
            'title' => 'SSD Customer Experience',
            'year' => '2023',
            'made' => 'Porta',
            'description' => 'Landing para destacar su producto uContact.',
            'link' => 'https://cx.ssd.com.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'npm',
                'vite',
                'figma',
                'lottie',
            ],
        ],
        (object) [
            'id' => 1,
            'title' => 'Bepsa',
            'year' => '2022',
            'made' => 'Porta',
            'description' => 'Sitio web institucional para la empresa Bepsa.',
            'link' => 'https://www.bepsa.com.py',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'npm',
                'jquery',
            ],
        ],
        (object) [
            'id' => 2,
            'title' => 'IPE Joyas',
            'year' => '2022',
            'made' => 'en equipo',
            'description' => 'Prototipo navegable en Figma para proyecto del diplomado UX/UI de la UCOM.',
            'link' => 'https://www.figma.com/proto/lyoRPX9nZogAsF9DmkkNcM/Hi-Fi-Prototype?type=design&scaling=min-zoom&page-id=0%3A1&starting-point-node-id=12%3A371&node-id=1-2',
            'github' => null,
            'badges' => [
                'figma',
            ],
        ],
        (object) [
            'id' => 2,
            'title' => 'Cappro',
            'year' => '2022',
            'made' => 'Porta',
            'description' => 'Sitio web institucional para la empresa Cappro.',
            'link' => 'https://cappro.org.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'jquery',
            ],
        ],
        (object) [
            'id' => 3,
            'title' => 'Luminotecnia',
            'year' => '2021',
            'made' => 'Porta',
            'description' => 'E-commerce para la empresa Luminotecnia. Desarrollo basado en el diseño original en Figma, convirtiendo los elementos visuales en código funcional.',
            'link' => 'https://www.luminotecnia.com.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'npm',
                'jquery',
                'figma',
            ],
        ],
                (object) [
            'id' => 8,
            'title' => 'It Card',
            'year' => '2021',
            'made' => 'Porta',
            'description' => 'E-commerce para las tiendas Mango, Springfield y Women Secret de It Card.',
            'link' => 'https://itcard.com.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'npm',
                'jquery',
            ],
        ],
        (object) [
            'id' => 4,
            'title' => 'Kemsa',
            'year' => '2021',
            'made' => 'Porta',
            'description' => 'E-commerce para las tiendas American Look, Sport House y Shoes 4 Less de Kemsa.',
            'link' => 'https://www.kemsa.com.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'npm',
                'jquery',
            ],
        ],
        (object) [
            'id' => 5,
            'title' => 'Electroban',
            'year' => '2020',
            'made' => 'Porta',
            'description' => 'E-commerce para Electroban.',
            'link' => 'https://www.electroban.com.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'npm',
                'jquery',
            ],
        ],
        (object) [
            'id' => 6,
            'title' => 'Sansei',
            'year' => '2020',
            'made' => 'Porta',
            'description' => 'E-commerce para Sansei. Desarrollo basado en el diseño original en Photoshop, convirtiendo los elementos visuales en código funcional.',
            'link' => 'https://www.sansei.com.py/',
            'github' => 'privado',
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'laravel',
                'jquery',
                'photoshop',
            ],
        ],
        (object) [
            'id' => 7,
            'title' => 'Landing Dior',
            'year' => '2020',
            'made' => 'Porta',
            'description' => 'Landing de productos Dior para Fuschia. Diseño aprobado por Dior Francia.',
            'link' => 'https://www.fuschia.com.py/dior-home',
            'github' => null,
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'jquery',
            ],
        ],
        (object) [
            'id' => 9,
            'title' => 'Grupo Luminotecnia',
            'year' => '2019',
            'made' => 'Porta',
            'description' => 'Sitio web institucional para Grupo Luminotecnia.',
            'link' => 'https://www.grupoluminotecnia.com.py/v2/',
            'github' => null,
            'badges' => [
                'html',
                'css',
                'bootstrap',
                'jquery',
            ],
        ],
    ],
];